resolver: lts-7.0
packages:
- '.'
- location:
    git: https://github.com/tvh/Xorshift128Plus.git
    commit: a8622ce87571285d8cc573baac4be7abcc322980
  extra-dep: true
- location:
    git: https://github.com/tvh/friday.git
    commit: 2327d744ff40170beb86f6f48b27f618b660a772 
  extra-dep: true
- location:
    git: https://github.com/tvh/friday-devil.git
    commit: 91fad2b36b21ded72f62fbb90e32bb7af2d2e36a
  extra-dep: true
- location:
    git: https://github.com/tvh/wavefront.git
    commit: 31cc777e9529041a1b72cc7343122960be692db4
  extra-dep: true
extra-deps:
- async-pool-0.9.0
- friday-juicypixels-0.1.2
- mersenne-random-1.0.0.1
- mersenne-random-pure64-0.2.2.0
- ratio-int-0.1.2
flags:
  mersenne-random:
    use_sse2: true
extra-package-dbs: []
require-stack-version: ">= 1.2.0"
nix:
  packages:
  - zlib
  - libdevil
  - ncurses
  - llvm_37
  - git
