resolver: nightly-2016-08-27
packages:
- '.'
- location: '../Xorshift128Plus'
  extra-dep: true
extra-deps:
- mersenne-random-pure64-0.2.2.0
- mersenne-random-1.0.0.1
flags:
  mersenne-random:
    use_sse2: true
extra-package-dbs: []
